openapi: 3.1.0
info:
  title: CookWithUs – Sharing
  version: 2.0.0
  description: Sharing bounded context – Recipe creation and lookup.

servers:
  - url: /api/v2

components:

  parameters:
    XCookId:
      name: X-Cook-Id
      in: header
      required: true
      schema:
        type: string
      description: ID of the Cook performing the action.

  schemas:

    Ingredient:
      type: object
      required: [name, number, unit]
      additionalProperties: false
      properties:
        name:
          type: string
        number:
          type: string
          description: Quantity as a free-form string (e.g. "3/4", "1.5").
        unit:
          type: string

    Step:
      type: object
      required: [orderNo, title, description]
      additionalProperties: false
      properties:
        orderNo:
          type: integer
          minimum: 1
        title:
          type: string
        description:
          type: string

    ShoppingItem:
      type: object
      required: [product, number]
      additionalProperties: false
      properties:
        product:
          type: string
        number:
          type: integer
          minimum: 1
        link:
          type: string

    Meal:
      type: string
      enum: [Breakfast, Lunch, Dinner, Dessert]

    Diet:
      type: string
      enum: [Normal, Vegetarian, Vegan]

    RecipeCreate:
      type: object
      required: [title, ingredients, howTo, servings, meal, diet]
      additionalProperties: false
      properties:
        title:
          type: string
        ingredients:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Ingredient'
        howTo:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Step'
        shoppingList:
          type: array
          items:
            $ref: '#/components/schemas/ShoppingItem'
        servings:
          type: integer
          minimum: 1
        meal:
          $ref: '#/components/schemas/Meal'
        diet:
          $ref: '#/components/schemas/Diet'
        picture:
          type: string
          description: Base64-encoded image. Optional.

    Recipe:
      type: object
      required: [id, ownerId, title, ingredients, howTo, servings, meal, diet]
      properties:
        id:
          type: string
        ownerId:
          type: string
        title:
          type: string
        ingredients:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Ingredient'
        howTo:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Step'
        shoppingList:
          type: array
          items:
            $ref: '#/components/schemas/ShoppingItem'
        servings:
          type: integer
          minimum: 1
        meal:
          $ref: '#/components/schemas/Meal'
        diet:
          $ref: '#/components/schemas/Diet'
        picture:
          type: string
          description: Base64-encoded image. Optional.

    Error:
      type: object
      required: [message]
      properties:
        message:
          type: string

paths:

  /recipes:
    post:
      operationId: shareRecipe
      summary: Share (create) a new Recipe
      tags: [Recipes]
      parameters:
        - $ref: '#/components/parameters/XCookId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeCreate'
      responses:
        '201':
          description: Recipe shared.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Validation error or duplicate title.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Missing or unknown X-Cook-Id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      operationId: listRecipes
      summary: List all Recipes
      tags: [Recipes]
      responses:
        '200':
          description: List of Recipes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'

  /recipes/{recipeId}:
    parameters:
      - name: recipeId
        in: path
        required: true
        schema:
          type: string

    get:
      operationId: getRecipe
      summary: Get a Recipe by ID
      tags: [Recipes]
      responses:
        '200':
          description: Recipe found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: Recipe not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
